services:
  accounts:
    image: "harsha2306/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - harsha2306
  loans:
    image: "harsha2306/loans:v1"
    container_name: loans-ms
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - harsha2306
  cards:
    image: "harsha2306/cards:v1"
    container_name: cards-ms
    ports:
      - "8083:8083"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - harsha2306
networks:
  harsha2306:
    driver: "bridge"