spring:
  application:
    name: gatewayserver
  main:
    banner-mode: off
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

logging:
  level:
    org:
      harsha:
        gatewayserver: DEBUG

info:
  app:
    name: "gateway server"
    description: "Gateway application"
    version: "1.0.0"
