spring:
  application:
    name: loans
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active: "prod"

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8082