spring:
  application:
    name: accounts
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: root
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  profiles:
    active: prod
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8081